# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a07ebadda96d40daeae3b4333d20e2de8afc9aaccb2f76f133922c500c8535845619d93c1c9bedf06f0f39e05109402a7a1d0f9c507d3f8dc8fcbbd472f636eb

test:
  secret_key_base: bdd4c889f91657b705e75382a4358b8b92885e85cdde9a370617a77dec7dc797d5a618336f81dd133ae727c842bfd6a1dc13237a2b4db54d671e478da0d557d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
